### PR TITLE
Fix data corruption

### PR DESCRIPTION
**Pull request by zqianem**
Hotfix for a data corruption issue where some scattered pixel values (most noticeable in wind speed data) were wrong

image

See the random blue pixels above

Will investigate further and report upstream when I have the time

### CODE REVIEW

**Comment by zqianem** [comment]
Ahhhg I really should have caught this when updating dependencies a couple weeks back.

Maybe this is the thing that finally motivates me to write some tests and/or make a script for downloading old data from archives = )

**Comment by zqianem** [comment]
Actually let's hold off on this hotfix as a proper fix is coming soon: https://github.com/petamoriken/float16/issues/1046#issuecomment-1722465697

**Comment by gravinamike** [comment]
Great - thanks Em! I will hold off on doing anything for now!

Mike Gravina
(508) 667-6162
***@***.***
________________________________

**Comment by zqianem** [comment]
Upstream fix was released, so instead of pinning the version this PR just updates all dependencies.

The failing Netlify checks can be ignored, looks like a cache issue that fixed itself on retry.

**Pull request merged**
